# 01. Capacitaciones (todas)

Proyecto de tesis (Maestria en Ciencia de Datos e IA, ESPOL): *Sistema de Generacion de Perfiles del Personal Docente y Administrativo en ESPOL para la asignacion inteligente de tareas*. Este notebook corresponde a la **Fase 1 y 2** de la metodologia: extraccion y depuracion de una de las fuentes institucionales que alimentan el catalogo de variables (historia laboral, capacitaciones, proyectos, experiencia y direcciones de tesis) usado para construir los perfiles multidimensionales del personal.

**Fuente:** `data/raw/capacitacionestodas.csv`  
**Salida:** `data/processed/capacitaciones_todas.csv`

Cursos, seminarios y diplomados tomados por el personal de ESPOL. Es una de las fuentes de formacion continua para el perfil de cada persona.

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd()))
import pandas as pd
import _preprocesamiento_comun as pc

pd.set_option('display.max_columns', 100)

## 1. Carga de datos crudos

In [2]:
df = pc.leer_csv('capacitacionestodas.csv', low_memory=False)
df.head()

Leido capacitacionestodas.csv con encoding=utf-8-sig -> 64563 filas, 62 columnas

,TIPODESCRIPCION,AREACAPACITACIONDESCRIPCION,TIPOMODALIDADDESCRIPCION,TIPOEVENTODESCRIPCION,NOMBREPAIS,IDCAPACITACION,IDPERSONA,NOMBRE,DURACION,FECHAINICIO,FECHAFIN,LUGARREALIZACION,TIPOCERTIFICADO,TIPOCAPACITACION,COSTO,AREAAPLICACION,INSTITUCION,TIPOINSTITUCION,PUNTAJEOBTENIDO,ULTIMO_CAMBIO,FECHAASCENSO,IDPAIS,IDCIUDAD,GRADOCATEGORIA,ANIO,TERMINO,IDAREA,ENTREGADO,IDINSTITUCION,TIPOPARTICIPACION,MODULO,TIPOEVENTO,AUSPICIANTE,DURACIONHORAS,NACIONALIDAD,CERTIFICADOPOR,NAMEARCHDOC,FORMACONOCIM,IDTIPOCONOCIMIEN,REVISADOPARAESCALAFON,ENESCALAFON,NAMEARCHDOC2,NAMEARCHDOC3,CONSIDERACOMISANT,NAMEDOCCOMISANT,REFARCHIVO1,REFARCHIVO2,REFARCHIVO3,REFARCHIVO4,INGRESORRHH,IDUSUARIO,IDREGISTROESCALAFONAPROB,FECHACHECKESCALAFON,TIPOMODALIDAD,GESTIONUATHESPOL,IDCANTON,ORIGENINGRESO,FECHASUBIDAARCHIVO,REFARCHIVOSENESCYT,FECHASUBIDAARCHIVOSENESCYT,ESTADOAPROBACION,FECHAAPROBACION
0,APROBACION,NaN,NaN,CURSO,ECUADOR,25152,9834,AUDITOR LÍDER ISO 9001,40.0,2012-06-04,NaN,NaN,AP,NaN,NaN,NaN,NaN,NaN,NaN,2016-07-18-16.54.25.606184,2016-07-18,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,7,NaN,NaN,NaN,SGS,NaN,R,2.0,N,N,NaN,NaN,NaN,NaN,"89547,88459",NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,N,NaN,WEB,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,TALLER,ECUADOR,18088,37950,ESTRÉS LABORAL,2.0,2015-12-10,2015-12-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-03-07-08.27.52.089918,2016-03-07,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,19,NaN,NaN,NaN,NaN,NaN,R,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,"37728,37329",NaN,NaN,NaN,S,76217.0,NaN,NaN,NaN,N,NaN,TH,NaN,NaN,NaN,NaN,NaN
2,APROBACION,NaN,NaN,CURSO,ECUADOR,18089,7415,AUTOMATIZACION INDUSTRIAL CON PLC LODO,16.0,2014-07-18,2014-07-19,NaN,AP,NaN,NaN,NaN,NaN,NaN,NaN,2016-03-07-09.37.32.452671,2016-03-07,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,7,NaN,NaN,NaN,NaN,NaN,R,2.0,NaN,NaN,NaN,NaN,NaN,NaN,"37729,37330",NaN,NaN,NaN,S,76217.0,NaN,NaN,NaN,N,NaN,TH,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,CURSO,ECUADOR,18090,7415,6234: IMPLEMENTING AND MAINTAÍNING MICROSOFT S...,30.0,2011-12-07,2012-01-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-03-07-09.39.22.122129,2016-03-07,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,7,NaN,NaN,NaN,NaN,NaN,R,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,"37730,37331",NaN,NaN,NaN,S,76217.0,NaN,NaN,NaN,N,NaN,TH,NaN,NaN,NaN,NaN,NaN
4,APROBACION,NaN,NaN,CURSO,ECUADOR,18091,7415,PLANIFICACIÓN Y EVALUACIÓN DE PRESUPUESTOS,30.0,2012-11-26,2012-11-30,NaN,AP,NaN,NaN,NaN,NaN,NaN,NaN,2016-03-07-09.40.46.199641,2016-03-07,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,7,NaN,NaN,NaN,NaN,NaN,R,2.0,NaN,NaN,NaN,NaN,NaN,NaN,"37731,37332",NaN,NaN,NaN,S,76217.0,NaN,NaN,NaN,N,NaN,TH,NaN,NaN,NaN,NaN,NaN

## 2. Exploración inicial

In [3]:
pc.resumen(df, 'capacitaciones_todas')

--- Resumen capacitaciones_todas ---
Dimensiones: 64563 filas x 62 columnas
Filas duplicadas: 0
Columnas con nulos (%):
LUGARREALIZACION               100.0
IDAREA                         100.0
PUNTAJEOBTENIDO                100.0
TIPOINSTITUCION                100.0
AREAAPLICACION                 100.0
ENTREGADO                      100.0
GRADOCATEGORIA                 100.0
ANIO                           100.0
TERMINO                        100.0
COSTO                          100.0
IDREGISTROESCALAFONAPROB       100.0
NACIONALIDAD                   100.0
AUSPICIANTE                    100.0
DURACIONHORAS                  100.0
REFARCHIVOSENESCYT             100.0
FECHASUBIDAARCHIVOSENESCYT     100.0
INSTITUCION                    100.0
NAMEARCHDOC3                   100.0
TIPOPARTICIPACION               99.9
NAMEARCHDOC2                    99.8
REFARCHIVO3                     99.7
NAMEDOCCOMISANT                 99.5
REFARCHIVO2                     98.6
REFARCHIVO4                     98.4
ESTADOAPROBACION                95.8
FECHAAPROBACION                 95.8
IDCANTON                        95.1
FECHACHECKESCALAFON             92.9
IDCIUDAD                        92.2
FECHASUBIDAARCHIVO              86.0
AREACAPACITACIONDESCRIPCION     80.7
TIPOCAPACITACION                80.7
NAMEARCHDOC                     78.1
IDUSUARIO                       68.0
IDINSTITUCION                   60.9
CONSIDERACOMISANT               56.7
TIPOMODALIDADDESCRIPCION        54.6
TIPOMODALIDAD                   53.0
ORIGENINGRESO                   33.8
IDTIPOCONOCIMIEN                17.0
REVISADOPARAESCALAFON           17.0
ENESCALAFON                     16.9
CERTIFICADOPOR                  15.2
TIPODESCRIPCION                 11.3
TIPOCERTIFICADO                 11.3
REFARCHIVO1                      3.1
FECHAFIN                         1.7
INGRESORRHH                      1.6
NOMBREPAIS                       1.3
MODULO                           0.0
dtype: float64

In [4]:
df.dtypes

TIPODESCRIPCION                    str
AREACAPACITACIONDESCRIPCION        str
TIPOMODALIDADDESCRIPCION           str
TIPOEVENTODESCRIPCION              str
NOMBREPAIS                         str
                                ...
FECHASUBIDAARCHIVO                 str
REFARCHIVOSENESCYT             float64
FECHASUBIDAARCHIVOSENESCYT     float64
ESTADOAPROBACION               float64
FECHAAPROBACION                    str
Length: 62, dtype: object

## 3. Limpieza

In [5]:
df = pc.limpiar_strings(df)
df = pc.quitar_columnas_vacias(df, umbral=0.99)
df = pc.quitar_columnas_constantes(df)

Columnas eliminadas por tener >= 99% de nulos: ['LUGARREALIZACION', 'COSTO', 'AREAAPLICACION', 'INSTITUCION', 'TIPOINSTITUCION', 'PUNTAJEOBTENIDO', 'GRADOCATEGORIA', 'ANIO', 'TERMINO', 'IDAREA', 'ENTREGADO', 'TIPOPARTICIPACION', 'AUSPICIANTE', 'DURACIONHORAS', 'NACIONALIDAD', 'NAMEARCHDOC2', 'NAMEARCHDOC3', 'NAMEDOCCOMISANT', 'REFARCHIVO3', 'IDREGISTROESCALAFONAPROB', 'REFARCHIVOSENESCYT', 'FECHASUBIDAARCHIVOSENESCYT']
Columnas eliminadas por ser constantes: ['MODULO', 'FORMACONOCIM', 'REVISADOPARAESCALAFON', 'ESTADOAPROBACION']

## 5. Tipado de fechas e identificadores

In [6]:
df = pc.castear_fechas(df, ['FECHAINICIO', 'FECHAFIN', 'ULTIMO_CAMBIO', 'FECHAASCENSO', 'FECHACHECKESCALAFON', 'FECHASUBIDAARCHIVO', 'FECHAAPROBACION'])
df = pc.castear_enteros(df, ['IDCAPACITACION', 'IDPERSONA', 'IDPAIS', 'IDCIUDAD', 'IDINSTITUCION', 'IDUSUARIO', 'IDCANTON', 'IDTIPOCONOCIMIEN'])

## 7. Verificación final

In [7]:
pc.resumen(df, 'capacitaciones_todas (procesado)')
df.head()

--- Resumen capacitaciones_todas (procesado) ---
Dimensiones: 64563 filas x 36 columnas
Filas duplicadas: 0
Columnas con nulos (%):
REFARCHIVO2                    98.6
REFARCHIVO4                    98.4
FECHAAPROBACION                95.8
IDCANTON                       95.1
FECHACHECKESCALAFON            92.9
IDCIUDAD                       92.2
FECHASUBIDAARCHIVO             86.0
AREACAPACITACIONDESCRIPCION    80.7
TIPOCAPACITACION               80.7
NAMEARCHDOC                    78.1
IDUSUARIO                      68.0
IDINSTITUCION                  60.9
CONSIDERACOMISANT              56.7
TIPOMODALIDADDESCRIPCION       54.6
TIPOMODALIDAD                  53.0
ORIGENINGRESO                  33.8
IDTIPOCONOCIMIEN               17.0
ENESCALAFON                    16.9
CERTIFICADOPOR                 15.2
TIPODESCRIPCION                11.3
TIPOCERTIFICADO                11.3
REFARCHIVO1                     3.1
FECHAFIN                        1.7
INGRESORRHH                     1.6
NOMBREPAIS                      1.3
dtype: float64

,TIPODESCRIPCION,AREACAPACITACIONDESCRIPCION,TIPOMODALIDADDESCRIPCION,TIPOEVENTODESCRIPCION,NOMBREPAIS,IDCAPACITACION,IDPERSONA,NOMBRE,DURACION,FECHAINICIO,FECHAFIN,TIPOCERTIFICADO,TIPOCAPACITACION,ULTIMO_CAMBIO,FECHAASCENSO,IDPAIS,IDCIUDAD,IDINSTITUCION,TIPOEVENTO,CERTIFICADOPOR,NAMEARCHDOC,IDTIPOCONOCIMIEN,ENESCALAFON,CONSIDERACOMISANT,REFARCHIVO1,REFARCHIVO2,REFARCHIVO4,INGRESORRHH,IDUSUARIO,FECHACHECKESCALAFON,TIPOMODALIDAD,GESTIONUATHESPOL,IDCANTON,ORIGENINGRESO,FECHASUBIDAARCHIVO,FECHAAPROBACION
0,APROBACION,<NA>,<NA>,CURSO,ECUADOR,25152,9834,AUDITOR LÍDER ISO 9001,40.0,2012-06-04,NaT,AP,<NA>,2016-07-18 16:54:25.606184,2016-07-18,1,<NA>,<NA>,7,SGS,<NA>,2,N,<NA>,"89547,88459",<NA>,<NA>,N,<NA>,NaT,<NA>,N,<NA>,WEB,NaT,NaT
1,<NA>,<NA>,<NA>,TALLER,ECUADOR,18088,37950,ESTRÉS LABORAL,2.0,2015-12-10,2015-12-10,<NA>,<NA>,2016-03-07 08:27:52.089918,2016-03-07,1,<NA>,<NA>,19,<NA>,<NA>,-1,<NA>,<NA>,"37728,37329",<NA>,<NA>,S,76217,NaT,<NA>,N,<NA>,TH,NaT,NaT
2,APROBACION,<NA>,<NA>,CURSO,ECUADOR,18089,7415,AUTOMATIZACION INDUSTRIAL CON PLC LODO,16.0,2014-07-18,2014-07-19,AP,<NA>,2016-03-07 09:37:32.452671,2016-03-07,1,<NA>,<NA>,7,<NA>,<NA>,2,<NA>,<NA>,"37729,37330",<NA>,<NA>,S,76217,NaT,<NA>,N,<NA>,TH,NaT,NaT
3,<NA>,<NA>,<NA>,CURSO,ECUADOR,18090,7415,6234: IMPLEMENTING AND MAINTAÍNING MICROSOFT S...,30.0,2011-12-07,2012-01-19,<NA>,<NA>,2016-03-07 09:39:22.122129,2016-03-07,1,<NA>,<NA>,7,<NA>,<NA>,-1,<NA>,<NA>,"37730,37331",<NA>,<NA>,S,76217,NaT,<NA>,N,<NA>,TH,NaT,NaT
4,APROBACION,<NA>,<NA>,CURSO,ECUADOR,18091,7415,PLANIFICACIÓN Y EVALUACIÓN DE PRESUPUESTOS,30.0,2012-11-26,2012-11-30,AP,<NA>,2016-03-07 09:40:46.199641,2016-03-07,1,<NA>,<NA>,7,<NA>,<NA>,2,<NA>,<NA>,"37731,37332",<NA>,<NA>,S,76217,NaT,<NA>,N,<NA>,TH,NaT,NaT

## 8. Guardado en data/processed

In [8]:
pc.guardar_procesado(df, 'capacitaciones_todas.csv')

Guardado: D:\Proyecto_Tesis\data\processed\capacitaciones_todas.csv (64563 filas x 36 columnas)

WindowsPath('D:/Proyecto_Tesis/data/processed/capacitaciones_todas.csv')