# 03. Carga politécnica disponible

Proyecto de tesis (Maestria en Ciencia de Datos e IA, ESPOL): *Sistema de Generacion de Perfiles del Personal Docente y Administrativo en ESPOL para la asignacion inteligente de tareas*. Este notebook corresponde a la **Fase 1 y 2** de la metodologia: extraccion y depuracion de una de las fuentes institucionales que alimentan el catalogo de variables (historia laboral, capacitaciones, proyectos, experiencia y direcciones de tesis) usado para construir los perfiles multidimensionales del personal.

**Fuente:** `data/raw/cargapolitecnicadisponible.csv`  
**Salida:** `data/processed/carga_politecnica_disponible.csv`

Funciones administrativas y de gestion asumidas por el personal academico (consejerias, direcciones, comisiones), fuera de la docencia directa. El archivo de origen presenta una corrupcion conocida de caracteres acentuados en nombres de unidades/funciones, que se repara antes de guardar.

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd()))
import pandas as pd
import _preprocesamiento_comun as pc

pd.set_option('display.max_columns', 100)

## 1. Carga de datos crudos

In [2]:
df = pc.leer_csv('cargapolitecnicadisponible.csv', low_memory=False)
df.head()

Leido cargapolitecnicadisponible.csv con encoding=utf-8-sig -> 48709 filas, 33 columnas

,IDPERSONA,NUMEROIDENTIFICACION,NOMDOCENTE,EMAIL,EMAILALTERNO,ANIO,TERMINO1,TERMINO2,TERMINO3,IDUNIDAD,IDUNIDADCARGA,NUMHORASCP,OBSERVACIONCP,NOMFUNCION,DESCFUNCION,IDPERIODO,VALOR,CODACADCARGA,NOMBREUNIDADCARGA,CODACAD,NOMBREUNIDAD,PERIODICIDAD,NUMHORAS,NIVELESTUDIO,NIVELGRADO,TERMINON1,TERMINON2,TERMINON3,APROBADO,IDTIPOACTIVIDAD,ACTIVIDAD,IDCENTRO,IDACTIVIDAD
0,37954,0920713526,ALMEIDA PAZMIÑO GONZALO ALFONSO,galmeida@espol.edu.ec,g_almeida_81@hotmail.com,2014,1.0,2.0,NaN,15007,15007,160,CARRERA IM,CONSEJERO ACADÉMICO,CARRERA IM,2014,Docencia,FIMP,Facultad de Ingeniería en Mecánica y Ciencias ...,FIMP,Facultad de Ingeniería en Mecánica y Ciencias ...,SEMANAL,4,R,PREGRADO,PRIMER TÉRMINO,SEGUNDO TÉRMINO,CURSO VACACIONAL,N,5,D,NaN,97
1,54259,0926470279,VILLACÍS TAGLE JACQUELINE ALEXANDRA,jaalvill@espol.edu.ec,jaktagle23@hotmail.com,2015,1.0,2.0,NaN,15249,15249,200,IINFORME SEMESTRAL A TRAVES DEL COORDINADOR DE...,PARTICIPACIÓN EN PROYECTO DE VÍNCULOS CON LA S...,IINFORME SEMESTRAL A TRAVES DEL COORDINADOR DE...,2015,Vínculos con la Colectividad,EDCOM,Escuela de Diseño y Comunicación Visual,EDCOM,Escuela de Diseño y Comunicación Visual,SEMANAL,5,R,PREGRADO,PRIMER TÉRMINO,SEGUNDO TÉRMINO,CURSO VACACIONAL,S,266,V,NaN,8573
2,53697,0925477457,JIMENEZ MIRANDA JOSÉ DAVID,jodajime@espol.edu.ec,zedavid88@hotmail.com,2016,1.0,2.0,NaN,15009,15287,200,COORDINADOR LAB. FISICA A,JEFE DE LABORATORIO DE DOCENCIA,COORDINADOR LAB. FISICA A,2016,Gestión Administrativa,FCNM,Facultad de Ciencias Naturales y Matemáticas,ICF,Instituto de Ciencias Físicas,SEMANAL,5,R,PREGRADO,PRIMER TÉRMINO,SEGUNDO TÉRMINO,CURSO VACACIONAL,S,582,A,NaN,13923
3,4860,0925018632,LOPEZ AGUIRRE MARIUXI ARACELY,marlopez@espol.edu.ec,lopmariuxi@gmail.com,2015,NaN,2.0,3.0,15008,15008,27,ARTÍCULO FEN OPINA.,ARTICULO ACADEMICO,ARTÍCULO FEN OPINA.,2015,Docencia,ICHE,Facultad de Ciencias Sociales y Humanísticas,ICHE,Facultad de Ciencias Sociales y Humanísticas,SEMANAL,1,R,PREGRADO,PRIMER TÉRMINO,SEGUNDO TÉRMINO,CURSO VACACIONAL,S,318,D,NaN,8575
4,76214,0910561372,ZURITA HURTADO HARRY ALFREDO,hazurita@espol.edu.ec,harry.zurita@gmail.com,2015,1.0,2.0,3.0,15287,15287,141,REUNIONES CONVOCADAS POR FCNM,ASISTENCIA Y PARTICIPACIÓN EN REUNIONES Y/O AC...,REUNIONES CONVOCADAS POR FCNM,2015,Docencia,FCNM,Facultad de Ciencias Naturales y Matemáticas,FCNM,Facultad de Ciencias Naturales y Matemáticas,SEMANAL,3,R,PREGRADO,PRIMER TÉRMINO,SEGUNDO TÉRMINO,CURSO VACACIONAL,S,259,D,NaN,8576

## 2. Exploración inicial

In [3]:
pc.resumen(df, 'carga_politecnica_disponible')

--- Resumen carga_politecnica_disponible ---
Dimensiones: 48709 filas x 33 columnas
Filas duplicadas: 0
Columnas con nulos (%):
IDCENTRO         99.3
TERMINO3         54.6
TERMINO1         19.9
TERMINO2         15.3
PERIODICIDAD      3.1
EMAILALTERNO      1.4
EMAIL             0.8
APROBADO          0.6
CODACADCARGA      0.1
CODACAD           0.1
DESCFUNCION       0.0
OBSERVACIONCP     0.0
dtype: float64

In [4]:
df.dtypes

IDPERSONA                 int64
NUMEROIDENTIFICACION        str
NOMDOCENTE                  str
EMAIL                       str
EMAILALTERNO                str
ANIO                      int64
TERMINO1                float64
TERMINO2                float64
TERMINO3                float64
IDUNIDAD                  int64
IDUNIDADCARGA             int64
NUMHORASCP                int64
OBSERVACIONCP               str
NOMFUNCION                  str
DESCFUNCION                 str
IDPERIODO                 int64
VALOR                       str
CODACADCARGA                str
NOMBREUNIDADCARGA           str
CODACAD                     str
NOMBREUNIDAD                str
PERIODICIDAD                str
NUMHORAS                  int64
NIVELESTUDIO                str
NIVELGRADO                  str
TERMINON1                   str
TERMINON2                   str
TERMINON3                   str
APROBADO                    str
IDTIPOACTIVIDAD           int64
ACTIVIDAD                   str
IDCENTRO                float64
IDACTIVIDAD               int64
dtype: object

## 3. Limpieza

In [5]:
df = pc.limpiar_strings(df)
df = pc.quitar_columnas_vacias(df, umbral=0.99)
df = pc.quitar_columnas_constantes(df)

Columnas eliminadas por tener >= 99% de nulos: ['IDCENTRO']
Columnas eliminadas por ser constantes: ['TERMINO1', 'TERMINO2', 'TERMINON1', 'TERMINON2', 'TERMINON3']

## 4. Reparación de caracteres corruptos

In [6]:
columnas_mojibake = ['NOMDOCENTE', 'NOMBREUNIDADCARGA', 'NOMBREUNIDAD', 'DESCFUNCION', 'OBSERVACIONCP', 'NOMFUNCION', 'ACTIVIDAD']
for col in columnas_mojibake:
    if col in df.columns:
        df[col] = pc.reparar_texto_latin1(df[col])
df[[c for c in columnas_mojibake if c in df.columns]].head()

,NOMDOCENTE,NOMBREUNIDADCARGA,NOMBREUNIDAD,DESCFUNCION,OBSERVACIONCP,NOMFUNCION,ACTIVIDAD
0,ALMEIDA PAZMIÑO GONZALO ALFONSO,Facultad de Ingeniería en Mecánica y Ciencias ...,Facultad de Ingeniería en Mecánica y Ciencias ...,CARRERA IM,CARRERA IM,CONSEJERO ACADÉMICO,D
1,VILLACÍS TAGLE JACQUELINE ALEXANDRA,Escuela de Diseño y Comunicación Visual,Escuela de Diseño y Comunicación Visual,IINFORME SEMESTRAL A TRAVES DEL COORDINADOR DE...,IINFORME SEMESTRAL A TRAVES DEL COORDINADOR DE...,PARTICIPACIÓN EN PROYECTO DE VÍNCULOS CON LA S...,V
2,JIMENEZ MIRANDA JOSÉ DAVID,Facultad de Ciencias Naturales y Matemáticas,Instituto de Ciencias Físicas,COORDINADOR LAB. FISICA A,COORDINADOR LAB. FISICA A,JEFE DE LABORATORIO DE DOCENCIA,A
3,LOPEZ AGUIRRE MARIUXI ARACELY,Facultad de Ciencias Sociales y Humanísticas,Facultad de Ciencias Sociales y Humanísticas,ARTÍCULO FEN OPINA.,ARTÍCULO FEN OPINA.,ARTICULO ACADEMICO,D
4,ZURITA HURTADO HARRY ALFREDO,Facultad de Ciencias Naturales y Matemáticas,Facultad de Ciencias Naturales y Matemáticas,REUNIONES CONVOCADAS POR FCNM,REUNIONES CONVOCADAS POR FCNM,ASISTENCIA Y PARTICIPACIÓN EN REUNIONES Y/O AC...,D

## 5. Tipado de fechas e identificadores

In [7]:
df = pc.castear_enteros(df, ['IDPERSONA', 'IDUNIDAD', 'IDUNIDADCARGA', 'IDPERIODO', 'IDTIPOACTIVIDAD', 'IDACTIVIDAD', 'IDCENTRO'])

## 7. Verificación final

In [8]:
pc.resumen(df, 'carga_politecnica_disponible (procesado)')
df.head()

--- Resumen carga_politecnica_disponible (procesado) ---
Dimensiones: 48709 filas x 27 columnas
Filas duplicadas: 0
Columnas con nulos (%):
TERMINO3         54.6
PERIODICIDAD      3.1
EMAILALTERNO      1.4
EMAIL             0.8
APROBADO          0.6
CODACADCARGA      0.1
CODACAD           0.1
OBSERVACIONCP     0.0
DESCFUNCION       0.0
dtype: float64

,IDPERSONA,NUMEROIDENTIFICACION,NOMDOCENTE,EMAIL,EMAILALTERNO,ANIO,TERMINO3,IDUNIDAD,IDUNIDADCARGA,NUMHORASCP,OBSERVACIONCP,NOMFUNCION,DESCFUNCION,IDPERIODO,VALOR,CODACADCARGA,NOMBREUNIDADCARGA,CODACAD,NOMBREUNIDAD,PERIODICIDAD,NUMHORAS,NIVELESTUDIO,NIVELGRADO,APROBADO,IDTIPOACTIVIDAD,ACTIVIDAD,IDACTIVIDAD
0,37954,0920713526,ALMEIDA PAZMIÑO GONZALO ALFONSO,galmeida@espol.edu.ec,g_almeida_81@hotmail.com,2014,NaN,15007,15007,160,CARRERA IM,CONSEJERO ACADÉMICO,CARRERA IM,2014,Docencia,FIMP,Facultad de Ingeniería en Mecánica y Ciencias ...,FIMP,Facultad de Ingeniería en Mecánica y Ciencias ...,SEMANAL,4,R,PREGRADO,N,5,D,97
1,54259,0926470279,VILLACÍS TAGLE JACQUELINE ALEXANDRA,jaalvill@espol.edu.ec,jaktagle23@hotmail.com,2015,NaN,15249,15249,200,IINFORME SEMESTRAL A TRAVES DEL COORDINADOR DE...,PARTICIPACIÓN EN PROYECTO DE VÍNCULOS CON LA S...,IINFORME SEMESTRAL A TRAVES DEL COORDINADOR DE...,2015,Vínculos con la Colectividad,EDCOM,Escuela de Diseño y Comunicación Visual,EDCOM,Escuela de Diseño y Comunicación Visual,SEMANAL,5,R,PREGRADO,S,266,V,8573
2,53697,0925477457,JIMENEZ MIRANDA JOSÉ DAVID,jodajime@espol.edu.ec,zedavid88@hotmail.com,2016,NaN,15009,15287,200,COORDINADOR LAB. FISICA A,JEFE DE LABORATORIO DE DOCENCIA,COORDINADOR LAB. FISICA A,2016,Gestión Administrativa,FCNM,Facultad de Ciencias Naturales y Matemáticas,ICF,Instituto de Ciencias Físicas,SEMANAL,5,R,PREGRADO,S,582,A,13923
3,4860,0925018632,LOPEZ AGUIRRE MARIUXI ARACELY,marlopez@espol.edu.ec,lopmariuxi@gmail.com,2015,3.0,15008,15008,27,ARTÍCULO FEN OPINA.,ARTICULO ACADEMICO,ARTÍCULO FEN OPINA.,2015,Docencia,ICHE,Facultad de Ciencias Sociales y Humanísticas,ICHE,Facultad de Ciencias Sociales y Humanísticas,SEMANAL,1,R,PREGRADO,S,318,D,8575
4,76214,0910561372,ZURITA HURTADO HARRY ALFREDO,hazurita@espol.edu.ec,harry.zurita@gmail.com,2015,3.0,15287,15287,141,REUNIONES CONVOCADAS POR FCNM,ASISTENCIA Y PARTICIPACIÓN EN REUNIONES Y/O AC...,REUNIONES CONVOCADAS POR FCNM,2015,Docencia,FCNM,Facultad de Ciencias Naturales y Matemáticas,FCNM,Facultad de Ciencias Naturales y Matemáticas,SEMANAL,3,R,PREGRADO,S,259,D,8576

## 8. Guardado en data/processed

In [9]:
pc.guardar_procesado(df, 'carga_politecnica_disponible.csv')

Guardado: D:\Proyecto_Tesis\data\processed\carga_politecnica_disponible.csv (48709 filas x 27 columnas)

WindowsPath('D:/Proyecto_Tesis/data/processed/carga_politecnica_disponible.csv')