# 09. Heteroevaluación disponible

Proyecto de tesis (Maestria en Ciencia de Datos e IA, ESPOL): *Sistema de Generacion de Perfiles del Personal Docente y Administrativo en ESPOL para la asignacion inteligente de tareas*. Este notebook corresponde a la **Fase 1 y 2** de la metodologia: extraccion y depuracion de una de las fuentes institucionales que alimentan el catalogo de variables (historia laboral, capacitaciones, proyectos, experiencia y direcciones de tesis) usado para construir los perfiles multidimensionales del personal.

**Fuente:** `data/raw/heteroevaluaciondisponible.csv`  
**Salida:** `data/processed/heteroevaluacion_disponible.csv`

Resultados de evaluacion docente por curso/paralelo/periodo (promedio, numero de evaluados). El archivo de origen trae la columna ANIO duplicada por un join previo.

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd()))
import pandas as pd
import _preprocesamiento_comun as pc

pd.set_option('display.max_columns', 100)

## 1. Carga de datos crudos

In [2]:
df = pc.leer_csv('heteroevaluaciondisponible.csv', low_memory=False)
df.head()

Leido heteroevaluaciondisponible.csv con encoding=utf-8-sig -> 76645 filas, 16 columnas

,ANIO,TERMINO,UNIDAD,IDCURSO,IDPERSONA,CODIGOMATERIA,ANIO.1,PARALELO,MATERIA,TIPOCURSO,IDENTIFICACION,APELLIDOS,NOMBRES,PROMEDIO,REGISTRADOS,EVALUADOS
0,2020,2S,FIMCP,142992.0,2834.0,MTRG1038,2020,1,SÍNTESIS DE MATERIALES,P,0920054202,PERUGACHI BENALCAZAR,CESAR RODRIGO,49.28,11,8
1,2020,2S,FIMCP,144371.0,1577.0,MTRG1028,2020,1,ESTRUCTURA Y CARACTERIZACIÓN DE MATERIALES,P,0914200290,CORNEJO MARTINEZ,MAURICIO HERIBERTO,89.00,12,10
2,2020,2S,FICT,138568.0,2161.0,MING1032,2020,101,"VENTILACIÓN, DRENAJE Y SISTEMAS ELÉCTRICOS",G,0917260853,ROMERO CRESPO,PAOLA LEONOR,99.64,5,4
3,2020,2S,FICT,138559.0,2103.0,MING1032,2020,1,"VENTILACIÓN, DRENAJE Y SISTEMAS ELÉCTRICOS",P,0917010332,CRESPO QUINTERO,JESÚS WASHINGTON,88.57,5,4
4,2020,2S,FCSH,144714.0,452.0,ARQG2043,2020,1,CAMPO DE ARQUEOLOGÍA II,P,0902282656,MARCOS PINO,JORGE GABRIEL,100.00,3,3

## 2. Exploración inicial

In [3]:
pc.resumen(df, 'heteroevaluacion_disponible')

--- Resumen heteroevaluacion_disponible ---
Dimensiones: 76645 filas x 16 columnas
Filas duplicadas: 1
Columnas con nulos (%):
IDCURSO      63.4
IDPERSONA     0.1
NOMBRES       0.0
APELLIDOS     0.0
dtype: float64

In [4]:
df.dtypes

ANIO                int64
TERMINO               str
UNIDAD                str
IDCURSO           float64
IDPERSONA         float64
CODIGOMATERIA         str
ANIO.1              int64
PARALELO              str
MATERIA               str
TIPOCURSO             str
IDENTIFICACION        str
APELLIDOS             str
NOMBRES               str
PROMEDIO          float64
REGISTRADOS         int64
EVALUADOS           int64
dtype: object

## 3. Limpieza

In [5]:
df = pc.limpiar_strings(df)
df = pc.quitar_columnas_vacias(df, umbral=0.99)
df = pc.quitar_columnas_constantes(df)
n_antes = len(df)
df = df.drop_duplicates().reset_index(drop=True)
print(f'Filas duplicadas eliminadas: {n_antes - len(df)}')

Filas duplicadas eliminadas: 1

## 5. Tipado de fechas e identificadores

In [6]:
df = pc.castear_enteros(df, ['IDCURSO', 'IDPERSONA'])

## 7. Verificación final

In [7]:
pc.resumen(df, 'heteroevaluacion_disponible (procesado)')
df.head()

--- Resumen heteroevaluacion_disponible (procesado) ---
Dimensiones: 76644 filas x 16 columnas
Filas duplicadas: 0
Columnas con nulos (%):
IDCURSO      63.4
IDPERSONA     0.1
NOMBRES       0.0
APELLIDOS     0.0
dtype: float64

,ANIO,TERMINO,UNIDAD,IDCURSO,IDPERSONA,CODIGOMATERIA,ANIO.1,PARALELO,MATERIA,TIPOCURSO,IDENTIFICACION,APELLIDOS,NOMBRES,PROMEDIO,REGISTRADOS,EVALUADOS
0,2020,2S,FIMCP,142992,2834,MTRG1038,2020,1,SÍNTESIS DE MATERIALES,P,0920054202,PERUGACHI BENALCAZAR,CESAR RODRIGO,49.28,11,8
1,2020,2S,FIMCP,144371,1577,MTRG1028,2020,1,ESTRUCTURA Y CARACTERIZACIÓN DE MATERIALES,P,0914200290,CORNEJO MARTINEZ,MAURICIO HERIBERTO,89.00,12,10
2,2020,2S,FICT,138568,2161,MING1032,2020,101,"VENTILACIÓN, DRENAJE Y SISTEMAS ELÉCTRICOS",G,0917260853,ROMERO CRESPO,PAOLA LEONOR,99.64,5,4
3,2020,2S,FICT,138559,2103,MING1032,2020,1,"VENTILACIÓN, DRENAJE Y SISTEMAS ELÉCTRICOS",P,0917010332,CRESPO QUINTERO,JESÚS WASHINGTON,88.57,5,4
4,2020,2S,FCSH,144714,452,ARQG2043,2020,1,CAMPO DE ARQUEOLOGÍA II,P,0902282656,MARCOS PINO,JORGE GABRIEL,100.00,3,3

## 8. Guardado en data/processed

In [8]:
pc.guardar_procesado(df, 'heteroevaluacion_disponible.csv')

Guardado: D:\Proyecto_Tesis\data\processed\heteroevaluacion_disponible.csv (76644 filas x 16 columnas)

WindowsPath('D:/Proyecto_Tesis/data/processed/heteroevaluacion_disponible.csv')