# 10. Historial laboral de personas

Proyecto de tesis (Maestria en Ciencia de Datos e IA, ESPOL): *Sistema de Generacion de Perfiles del Personal Docente y Administrativo en ESPOL para la asignacion inteligente de tareas*. Este notebook corresponde a la **Fase 1 y 2** de la metodologia: extraccion y depuracion de una de las fuentes institucionales que alimentan el catalogo de variables (historia laboral, capacitaciones, proyectos, experiencia y direcciones de tesis) usado para construir los perfiles multidimensionales del personal.

**Fuente:** `data/raw/historialaboralpersonas.csv`  
**Salida:** `data/processed/historial_laboral_personas.csv`

Historial de contratos del personal en ESPOL (cargo, tipo de contrato, fechas, unidad). En este extracto contiene los contratos de una persona a modo de muestra.

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd()))
import pandas as pd
import _preprocesamiento_comun as pc

pd.set_option('display.max_columns', 100)

## 1. Carga de datos crudos

In [2]:
df = pc.leer_csv('historialaboralpersonas.csv', low_memory=False)
df.head()

Leido historialaboralpersonas.csv con encoding=utf-8-sig -> 17 filas, 35 columnas

,IDPERSONA,IDENTIFICACION,NOMBRES,APELLIDOS,IDCONTRATOLABORAL,CARGO,IDCARGO,CONTRATO,ESTADOCONTRATO,ESTADO,FECHAINICIOCONTRATO,FECHAFINCONTRATO,NOMBRETABLA,IDUNIDAD,MODULO,HORARIOFLEXIBLE,IDREGIMENLABORAL,TIPOEMPLEADO,FECHAVIGENCIA,FECHADESVINCULACION,HORAS,FECHAINGRESOESPOL,TIPODEDICACION,NROCONTRATO,ESPORCONCURSO,NIVELDOCENCIA,RMU,IDUBICACIONFISICAEMP,REFARCHIVO1,REFARCHIVO2,TIPO,FECHAREGISTRO,IDUSUARIO,IDUNIDADACADEMICAFIS,TIPOVINCULO
0,96832,925353146,CARLOS LUIS,SANCHEZ ACOSTA,8676,SERVICIOS PROFESIONALES - EJECUCIÓN DE ACTIVID...,NaN,CONTRATO CIVIL,FF,FINALIZADO,2022-10-03,2022-10-14,TBL_CONTRATACION_OTROS,435,N,N,0,AA,2022-10-14,2022-10-14,40,2021-09-16,NaN,DTH-SC-591-2022,NO,NaN,500.0,17046,"777123,734731",NaN,V,2022-09-30,651029,15312,SIN REL. DEPENDENCIA
1,96832,925353146,CARLOS LUIS,SANCHEZ ACOSTA,7429,TÉCNICOS ESPECIALIZADOS - EJECUCIÓN DE PROYECTOS,NaN,CONTRATO CIVIL,FF,FINALIZADO,2021-09-16,2021-12-31,TBL_CONTRATACION_OTROS,103,N,N,0,AA,2021-12-31,2021-12-31,40,2021-09-16,NaN,DTH-SC-473-2021,NO,NaN,817.0,15118,"480284,482699",NaN,V,2021-09-13,54860,15296,SIN REL. DEPENDENCIA
2,96832,925353146,CARLOS LUIS,SANCHEZ ACOSTA,7904,TÉCNICOS ESPECIALIZADOS - EJECUCIÓN DE PROYECTOS,NaN,CONTRATO CIVIL,FF,FINALIZADO,2022-01-06,2022-12-31,TBL_CONTRATACION_OTROS,103,N,N,0,AA,2022-12-31,2022-01-31,40,2021-09-16,NaN,DTH-SC-185-2022,NO,NaN,817.0,16028,"562252,547017",NaN,V,2022-01-12,651029,15296,SIN REL. DEPENDENCIA
3,96832,925353146,CARLOS LUIS,SANCHEZ ACOSTA,7996,SERVICIOS PROFESIONALES - EJECUCIÓN DE ACTIVID...,NaN,CONTRATO CIVIL,FF,FINALIZADO,2022-02-01,2022-12-30,TBL_CONTRATACION_OTROS,103,N,N,0,AA,2022-12-30,2022-12-30,40,2021-09-16,NaN,DTH-SC-247-2022,NO,NaN,1212.0,16167,"610749,571074",NaN,V,2022-02-01,651029,15296,SIN REL. DEPENDENCIA
4,96832,925353146,CARLOS LUIS,SANCHEZ ACOSTA,9195,SERVICIOS PROFESIONALES - EJECUCIÓN DE ACTIVID...,NaN,CONTRATO CIVIL,FF,FINALIZADO,2023-01-09,2023-12-31,TBL_CONTRATACION_OTROS,103,N,N,0,AA,2023-12-31,2023-12-31,40,2021-09-16,NaN,DTH-SC-201-2023,NO,NaN,1212.0,17746,"834025,790372",NaN,V,2023-01-13,651029,15296,SIN REL. DEPENDENCIA

## 2. Exploración inicial

In [3]:
pc.resumen(df, 'historial_laboral_personas')

--- Resumen historial_laboral_personas ---
Dimensiones: 17 filas x 35 columnas
Filas duplicadas: 0
Columnas con nulos (%):
NIVELDOCENCIA          100.0
TIPODEDICACION         100.0
FECHAVIGENCIA           70.6
FECHADESVINCULACION     70.6
REFARCHIVO2             58.8
IDCARGO                 29.4
FECHAFINCONTRATO         5.9
dtype: float64

In [4]:
df.dtypes

IDPERSONA                 int64
IDENTIFICACION            int64
NOMBRES                     str
APELLIDOS                   str
IDCONTRATOLABORAL         int64
CARGO                       str
IDCARGO                 float64
CONTRATO                    str
ESTADOCONTRATO              str
ESTADO                      str
FECHAINICIOCONTRATO         str
FECHAFINCONTRATO            str
NOMBRETABLA                 str
IDUNIDAD                  int64
MODULO                      str
HORARIOFLEXIBLE             str
IDREGIMENLABORAL          int64
TIPOEMPLEADO                str
FECHAVIGENCIA               str
FECHADESVINCULACION         str
HORAS                     int64
FECHAINGRESOESPOL           str
TIPODEDICACION          float64
NROCONTRATO                 str
ESPORCONCURSO               str
NIVELDOCENCIA           float64
RMU                     float64
IDUBICACIONFISICAEMP      int64
REFARCHIVO1                 str
REFARCHIVO2                 str
TIPO                        str
FECHAREGISTRO               str
IDUSUARIO                 int64
IDUNIDADACADEMICAFIS      int64
TIPOVINCULO                 str
dtype: object

## 3. Limpieza

In [5]:
df = pc.limpiar_strings(df)
df = pc.quitar_columnas_vacias(df, umbral=0.99)
df = pc.quitar_columnas_constantes(df)

Columnas eliminadas por tener >= 99% de nulos: ['TIPODEDICACION', 'NIVELDOCENCIA']
Columnas eliminadas por ser constantes: ['IDPERSONA', 'IDENTIFICACION', 'NOMBRES', 'APELLIDOS', 'IDCARGO', 'HORARIOFLEXIBLE', 'TIPOEMPLEADO', 'FECHAINGRESOESPOL', 'ESPORCONCURSO']

## 5. Tipado de fechas e identificadores

In [6]:
df = pc.castear_fechas(df, ['FECHAINICIOCONTRATO', 'FECHAFINCONTRATO', 'FECHAVIGENCIA', 'FECHADESVINCULACION', 'FECHAINGRESOESPOL', 'FECHAREGISTRO'])
df = pc.castear_enteros(df, ['IDPERSONA', 'IDCONTRATOLABORAL', 'IDCARGO', 'IDUNIDAD', 'IDUBICACIONFISICAEMP', 'IDUSUARIO', 'IDUNIDADACADEMICAFIS'])

## 7. Verificación final

In [7]:
pc.resumen(df, 'historial_laboral_personas (procesado)')
df.head()

--- Resumen historial_laboral_personas (procesado) ---
Dimensiones: 17 filas x 24 columnas
Filas duplicadas: 0
Columnas con nulos (%):
FECHADESVINCULACION    70.6
FECHAVIGENCIA          70.6
REFARCHIVO2            58.8
FECHAFINCONTRATO        5.9
dtype: float64

,IDCONTRATOLABORAL,CARGO,CONTRATO,ESTADOCONTRATO,ESTADO,FECHAINICIOCONTRATO,FECHAFINCONTRATO,NOMBRETABLA,IDUNIDAD,MODULO,IDREGIMENLABORAL,FECHAVIGENCIA,FECHADESVINCULACION,HORAS,NROCONTRATO,RMU,IDUBICACIONFISICAEMP,REFARCHIVO1,REFARCHIVO2,TIPO,FECHAREGISTRO,IDUSUARIO,IDUNIDADACADEMICAFIS,TIPOVINCULO
0,8676,SERVICIOS PROFESIONALES - EJECUCIÓN DE ACTIVID...,CONTRATO CIVIL,FF,FINALIZADO,2022-10-03,2022-10-14,TBL_CONTRATACION_OTROS,435,N,0,2022-10-14,2022-10-14,40,DTH-SC-591-2022,500.0,17046,"777123,734731",<NA>,V,2022-09-30,651029,15312,SIN REL. DEPENDENCIA
1,7429,TÉCNICOS ESPECIALIZADOS - EJECUCIÓN DE PROYECTOS,CONTRATO CIVIL,FF,FINALIZADO,2021-09-16,2021-12-31,TBL_CONTRATACION_OTROS,103,N,0,2021-12-31,2021-12-31,40,DTH-SC-473-2021,817.0,15118,"480284,482699",<NA>,V,2021-09-13,54860,15296,SIN REL. DEPENDENCIA
2,7904,TÉCNICOS ESPECIALIZADOS - EJECUCIÓN DE PROYECTOS,CONTRATO CIVIL,FF,FINALIZADO,2022-01-06,2022-12-31,TBL_CONTRATACION_OTROS,103,N,0,2022-12-31,2022-01-31,40,DTH-SC-185-2022,817.0,16028,"562252,547017",<NA>,V,2022-01-12,651029,15296,SIN REL. DEPENDENCIA
3,7996,SERVICIOS PROFESIONALES - EJECUCIÓN DE ACTIVID...,CONTRATO CIVIL,FF,FINALIZADO,2022-02-01,2022-12-30,TBL_CONTRATACION_OTROS,103,N,0,2022-12-30,2022-12-30,40,DTH-SC-247-2022,1212.0,16167,"610749,571074",<NA>,V,2022-02-01,651029,15296,SIN REL. DEPENDENCIA
4,9195,SERVICIOS PROFESIONALES - EJECUCIÓN DE ACTIVID...,CONTRATO CIVIL,FF,FINALIZADO,2023-01-09,2023-12-31,TBL_CONTRATACION_OTROS,103,N,0,2023-12-31,2023-12-31,40,DTH-SC-201-2023,1212.0,17746,"834025,790372",<NA>,V,2023-01-13,651029,15296,SIN REL. DEPENDENCIA

## 8. Guardado en data/processed

In [8]:
pc.guardar_procesado(df, 'historial_laboral_personas.csv')

Guardado: D:\Proyecto_Tesis\data\processed\historial_laboral_personas.csv (17 filas x 24 columnas)

WindowsPath('D:/Proyecto_Tesis/data/processed/historial_laboral_personas.csv')