# 12. Mención de honor

Proyecto de tesis (Maestria en Ciencia de Datos e IA, ESPOL): *Sistema de Generacion de Perfiles del Personal Docente y Administrativo en ESPOL para la asignacion inteligente de tareas*. Este notebook corresponde a la **Fase 1 y 2** de la metodologia: extraccion y depuracion de una de las fuentes institucionales que alimentan el catalogo de variables (historia laboral, capacitaciones, proyectos, experiencia y direcciones de tesis) usado para construir los perfiles multidimensionales del personal.

**Fuente:** `data/raw/mencionhonor.csv`  
**Salida:** `data/processed/mencion_honor.csv`

Menciones de honor / distinciones academicas obtenidas por el personal.

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd()))
import pandas as pd
import _preprocesamiento_comun as pc

pd.set_option('display.max_columns', 100)

## 1. Carga de datos crudos

In [2]:
df = pc.leer_csv('mencionhonor.csv', low_memory=False)
df.head()

Leido mencionhonor.csv con encoding=utf-8-sig -> 5457 filas, 12 columnas

,IDMENCIONHONOR,NOMBREMENCION,IDINSTITUCION,IDPAIS,ULTIMO_CAMBIO,IDPERSONA,FECHA,INSTITUCION,REFARCHIVO,TIPO,SITIOWEB,IDUSUARIO
0,1480,SEGUNDA MENCIÓN DE HONOR,NaN,1,2016-03-09-10.22.57.442071,76290,2002-09-05,UNIVERSIDAD DE GUAYAQUIL,NaN,NaN,NaN,NaN
1,1481,DIPLOMA DE HONOR,NaN,1,2016-03-10-15.46.15.340093,54029,2010-10-28,LA ESCUELA SUPERIOR POLITÉCNICA DEL LITORAL,NaN,NaN,NaN,NaN
2,1482,MEDALLA DE ORO Y DIPLOMA DE HONOR,NaN,1,2016-03-10-15.47.10.588984,54029,2010-10-29,LA ESCUELA SUPERIOR POLITÉCNICA DEL LITORAL,NaN,NaN,NaN,NaN
3,1483,TINKER RESEARCH FIELD GRANT,NaN,4,2016-03-11-23.03.43.754136,7726,2016-02-09,LATIN AMERICAN AND CARIBEAN CENTER/ FLORIDA IN...,NaN,NaN,NaN,NaN
4,1484,CERTIFICACIÓN HONORÍFICA,NaN,1,2016-03-15-14.52.28.872800,86531,2010-02-19,UNIVERSIDAD CATÓLICA DE SANTIAGO DE GUAYAQUIL,NaN,NaN,NaN,NaN

## 2. Exploración inicial

In [3]:
pc.resumen(df, 'mencion_honor')

--- Resumen mencion_honor ---
Dimensiones: 5457 filas x 12 columnas
Filas duplicadas: 0
Columnas con nulos (%):
IDUSUARIO        98.2
SITIOWEB         81.7
IDINSTITUCION    80.6
TIPO             74.2
REFARCHIVO       40.9
INSTITUCION       1.3
dtype: float64

In [4]:
df.dtypes

IDMENCIONHONOR      int64
NOMBREMENCION         str
IDINSTITUCION     float64
IDPAIS              int64
ULTIMO_CAMBIO         str
IDPERSONA           int64
FECHA                 str
INSTITUCION           str
REFARCHIVO            str
TIPO                  str
SITIOWEB              str
IDUSUARIO         float64
dtype: object

## 3. Limpieza

In [5]:
df = pc.limpiar_strings(df)
df = pc.quitar_columnas_vacias(df, umbral=0.99)
df = pc.quitar_columnas_constantes(df)

## 5. Tipado de fechas e identificadores

In [6]:
df = pc.castear_fechas(df, ['ULTIMO_CAMBIO', 'FECHA'])
df = pc.castear_enteros(df, ['IDMENCIONHONOR', 'IDINSTITUCION', 'IDPAIS', 'IDPERSONA', 'IDUSUARIO'])

## 7. Verificación final

In [7]:
pc.resumen(df, 'mencion_honor (procesado)')
df.head()

--- Resumen mencion_honor (procesado) ---
Dimensiones: 5457 filas x 12 columnas
Filas duplicadas: 0
Columnas con nulos (%):
IDUSUARIO        98.2
SITIOWEB         81.7
IDINSTITUCION    80.6
TIPO             74.2
REFARCHIVO       40.9
INSTITUCION       1.3
dtype: float64

,IDMENCIONHONOR,NOMBREMENCION,IDINSTITUCION,IDPAIS,ULTIMO_CAMBIO,IDPERSONA,FECHA,INSTITUCION,REFARCHIVO,TIPO,SITIOWEB,IDUSUARIO
0,1480,SEGUNDA MENCIÓN DE HONOR,<NA>,1,2016-03-09 10:22:57.442071,76290,2002-09-05,UNIVERSIDAD DE GUAYAQUIL,<NA>,<NA>,<NA>,<NA>
1,1481,DIPLOMA DE HONOR,<NA>,1,2016-03-10 15:46:15.340093,54029,2010-10-28,LA ESCUELA SUPERIOR POLITÉCNICA DEL LITORAL,<NA>,<NA>,<NA>,<NA>
2,1482,MEDALLA DE ORO Y DIPLOMA DE HONOR,<NA>,1,2016-03-10 15:47:10.588984,54029,2010-10-29,LA ESCUELA SUPERIOR POLITÉCNICA DEL LITORAL,<NA>,<NA>,<NA>,<NA>
3,1483,TINKER RESEARCH FIELD GRANT,<NA>,4,2016-03-11 23:03:43.754136,7726,2016-02-09,LATIN AMERICAN AND CARIBEAN CENTER/ FLORIDA IN...,<NA>,<NA>,<NA>,<NA>
4,1484,CERTIFICACIÓN HONORÍFICA,<NA>,1,2016-03-15 14:52:28.872800,86531,2010-02-19,UNIVERSIDAD CATÓLICA DE SANTIAGO DE GUAYAQUIL,<NA>,<NA>,<NA>,<NA>

## 8. Guardado en data/processed

In [8]:
pc.guardar_procesado(df, 'mencion_honor.csv')

Guardado: D:\Proyecto_Tesis\data\processed\mencion_honor.csv (5457 filas x 12 columnas)

WindowsPath('D:/Proyecto_Tesis/data/processed/mencion_honor.csv')