# 13. Ponentes (todos)

Proyecto de tesis (Maestria en Ciencia de Datos e IA, ESPOL): *Sistema de Generacion de Perfiles del Personal Docente y Administrativo en ESPOL para la asignacion inteligente de tareas*. Este notebook corresponde a la **Fase 1 y 2** de la metodologia: extraccion y depuracion de una de las fuentes institucionales que alimentan el catalogo de variables (historia laboral, capacitaciones, proyectos, experiencia y direcciones de tesis) usado para construir los perfiles multidimensionales del personal.

**Fuente:** `data/raw/ponentestodos.csv`  
**Salida:** `data/processed/ponentes_todos.csv`

Participaciones como ponente en congresos y eventos (subconjunto de capacitaciones con TIPOEVENTODESCRIPCION = CONGRESO). Comparte esquema con capacitaciones_todas y certificados_todos.

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd()))
import pandas as pd
import _preprocesamiento_comun as pc

pd.set_option('display.max_columns', 100)

## 1. Carga de datos crudos

In [2]:
df = pc.leer_csv('ponentestodos.csv', low_memory=False)
df.head()

Leido ponentestodos.csv con encoding=utf-8-sig -> 1257 filas, 62 columnas

,TIPODESCRIPCION,AREAACITACIONDESCRIPCION,TIPOMODALIDADDESCRIPCION,TIPOEVENTODESCRIPCION,NOMBREPAIS,IDCAPACITACION,IDPERSONA,NOMBRE,DURACION,FECHAINICIO,FECHAFIN,LUGARREALIZACION,TIPOCERTIFICADO,TIPOCAPACITACION,COSTO,AREAAPLICACION,INSTITUCION,TIPOINSTITUCION,PUNTAJEOBTENIDO,ULTIMO_CAMBIO,FECHAASCENSO,IDPAIS,IDCIUDAD,GRADOCATEGORIA,ANIO,TERMINO,IDAREA,ENTREGADO,IDINSTITUCION,TIPOPARTICIPACION,MODULO,TIPOEVENTO,AUSPICIANTE,DURACIONHORAS,NACIONALIDAD,CERTIFICADOPOR,NAMEARCHDOC,FORMACONOCIM,IDTIPOCONOCIMIEN,REVISADOPARAESCALAFON,ENESCALAFON,NAMEARCHDOC2,NAMEARCHDOC3,CONSIDERACOMISANT,NAMEDOCCOMISANT,REFARCHIVO1,REFARCHIVO2,REFARCHIVO3,REFARCHIVO4,INGRESORRHH,IDUSUARIO,IDREGISTROESCALAFONAPROB,FECHACHECKESCALAFON,TIPOMODALIDAD,GESTIONUATHESPOL,IDCANTON,ORIGENINGRESO,FECHASUBIDAARCHIVO,REFARCHIVOSENESCYT,FECHASUBIDAARCHIVOSENESCYT,ESTADOAPROBACION,FECHAAPROBACION
0,NaN,NaN,VIRTUAL,CONGRESO,NaN,65483,102915,ISFSEA 2025 / CHAOS-PRESERVING FUZZY DIFFERENC...,0.5,2025-05-05,2025-05-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-05-18-20.09.38.143757,2025-05-18,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,D,5,NaN,NaN,NaN,The international Society of Fuzzy Sets Extens...,NaN,I,NaN,N,N,NaN,NaN,N,NaN,"1671198,1574397",NaN,NaN,NaN,N,NaN,NaN,NaN,L,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,CONGRESO,ECUADOR,29105,3471,"ESPOLCIENCIA 2007, AFICHES PRIMER LUGAR: METOD...",8.0,2007-11-14,2007-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-04-24-19.07.04.592696,2017-04-19,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,5,NaN,NaN,NaN,NaN,NaN,I,-1.0,N,S,NaN,NaN,S,NaN,"128000,127181",NaN,NaN,"127999,127180",N,NaN,NaN,2017-04-24,NaN,N,NaN,WEB,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,CONGRESO,ECUADOR,2060,7374,III CONGRESO INTERNACIONAL DE ACUACULTURA EN A...,32.0,2013-07-11,2013-07-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-30-13.36.57.776130,2014-07-08,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,5,NaN,NaN,NaN,NaN,EA0908984644-CAP_1_BAYOT_ARROYO_BONNY.PDF,I,-1.0,N,N,NaN,NaN,N,NaN,"19724,19465",NaN,NaN,NaN,S,76217.0,NaN,NaN,NaN,N,NaN,TH,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,CONGRESO,ECUADOR,2132,5388,I CONGRESO DE FORMACION ACADEMICA ENFOQUE: CAMPO,6.0,2011-12-15,2011-12-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-02-14-14.01.53.065468,2014-07-15,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,5,NaN,NaN,NaN,NaN,EA0914776042-FIMCBOR_CAP_2011_1_CALLES_PROCEL.PDF,I,-1.0,N,N,NaN,NaN,N,NaN,"19793,19534",NaN,NaN,NaN,S,76217.0,NaN,NaN,NaN,N,NaN,TH,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,CONGRESO,ECUADOR,29106,3471,BITWORLD 2002: COMMERCIALIZATION AND DEVELOPME...,24.0,2002-06-03,2002-06-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-04-24-10.52.03.980839,2017-04-19,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,5,NaN,NaN,NaN,NaN,NaN,I,-1.0,N,S,NaN,NaN,S,NaN,"128004,127185",NaN,NaN,"128003,127184",N,NaN,NaN,2017-04-24,NaN,N,NaN,WEB,NaN,NaN,NaN,NaN,NaN

## 2. Exploración inicial

In [3]:
pc.resumen(df, 'ponentes_todos')

--- Resumen ponentes_todos ---
Dimensiones: 1257 filas x 62 columnas
Filas duplicadas: 0
Columnas con nulos (%):
LUGARREALIZACION              100.0
PUNTAJEOBTENIDO               100.0
TIPOINSTITUCION               100.0
IDAREA                        100.0
ENTREGADO                     100.0
TIPOPARTICIPACION             100.0
GRADOCATEGORIA                100.0
ANIO                          100.0
TERMINO                       100.0
COSTO                         100.0
AREAAPLICACION                100.0
INSTITUCION                   100.0
AUSPICIANTE                   100.0
DURACIONHORAS                 100.0
NAMEDOCCOMISANT               100.0
IDREGISTROESCALAFONAPROB      100.0
REFARCHIVOSENESCYT            100.0
FECHASUBIDAARCHIVOSENESCYT    100.0
NACIONALIDAD                  100.0
NAMEARCHDOC3                   99.8
NAMEARCHDOC2                   99.4
IDCANTON                       99.0
IDCIUDAD                       98.8
REFARCHIVO3                    98.4
REFARCHIVO4                    98.2
FECHAAPROBACION                98.0
ESTADOAPROBACION               98.0
TIPODESCRIPCION                94.8
TIPOCERTIFICADO                94.8
REFARCHIVO2                    94.0
NAMEARCHDOC                    86.0
FECHACHECKESCALAFON            84.6
FECHASUBIDAARCHIVO             83.5
TIPOCAPACITACION               79.4
AREAACITACIONDESCRIPCION       79.4
IDUSUARIO                      77.3
CERTIFICADOPOR                 74.0
TIPOMODALIDADDESCRIPCION       58.8
TIPOMODALIDAD                  57.8
IDINSTITUCION                  56.2
CONSIDERACOMISANT              49.2
IDTIPOCONOCIMIEN               43.1
ORIGENINGRESO                  42.9
REFARCHIVO1                    13.2
INGRESORRHH                     4.4
REVISADOPARAESCALAFON           4.2
ENESCALAFON                     3.9
FECHAFIN                        1.8
NOMBREPAIS                      0.1
dtype: float64

In [4]:
df.dtypes

TIPODESCRIPCION                   str
AREAACITACIONDESCRIPCION          str
TIPOMODALIDADDESCRIPCION          str
TIPOEVENTODESCRIPCION             str
NOMBREPAIS                        str
                               ...
FECHASUBIDAARCHIVO                str
REFARCHIVOSENESCYT            float64
FECHASUBIDAARCHIVOSENESCYT    float64
ESTADOAPROBACION              float64
FECHAAPROBACION                   str
Length: 62, dtype: object

## 3. Limpieza

In [5]:
df = pc.limpiar_strings(df)
df = pc.quitar_columnas_vacias(df, umbral=0.99)
df = pc.quitar_columnas_constantes(df)

Columnas eliminadas por tener >= 99% de nulos: ['LUGARREALIZACION', 'COSTO', 'AREAAPLICACION', 'INSTITUCION', 'TIPOINSTITUCION', 'PUNTAJEOBTENIDO', 'GRADOCATEGORIA', 'ANIO', 'TERMINO', 'IDAREA', 'ENTREGADO', 'TIPOPARTICIPACION', 'AUSPICIANTE', 'DURACIONHORAS', 'NACIONALIDAD', 'NAMEARCHDOC2', 'NAMEARCHDOC3', 'NAMEDOCCOMISANT', 'IDREGISTROESCALAFONAPROB', 'REFARCHIVOSENESCYT', 'FECHASUBIDAARCHIVOSENESCYT']
Columnas eliminadas por ser constantes: ['TIPOEVENTODESCRIPCION', 'IDINSTITUCION', 'MODULO', 'TIPOEVENTO', 'FORMACONOCIM', 'REVISADOPARAESCALAFON', 'GESTIONUATHESPOL', 'ESTADOAPROBACION']

## 5. Tipado de fechas e identificadores

In [6]:
df = pc.castear_fechas(df, ['FECHAINICIO', 'FECHAFIN', 'ULTIMO_CAMBIO', 'FECHAASCENSO', 'FECHACHECKESCALAFON', 'FECHASUBIDAARCHIVO', 'FECHAAPROBACION'])
df = pc.castear_enteros(df, ['IDCAPACITACION', 'IDPERSONA', 'IDPAIS', 'IDCIUDAD', 'IDINSTITUCION', 'IDUSUARIO', 'IDCANTON', 'IDTIPOCONOCIMIEN'])

## 7. Verificación final

In [7]:
pc.resumen(df, 'ponentes_todos (procesado)')
df.head()

--- Resumen ponentes_todos (procesado) ---
Dimensiones: 1257 filas x 33 columnas
Filas duplicadas: 0
Columnas con nulos (%):
IDCANTON                    99.0
IDCIUDAD                    98.8
REFARCHIVO3                 98.4
REFARCHIVO4                 98.2
FECHAAPROBACION             98.0
TIPODESCRIPCION             94.8
TIPOCERTIFICADO             94.8
REFARCHIVO2                 94.0
NAMEARCHDOC                 86.0
FECHACHECKESCALAFON         84.6
FECHASUBIDAARCHIVO          83.5
AREAACITACIONDESCRIPCION    79.4
TIPOCAPACITACION            79.4
IDUSUARIO                   77.3
CERTIFICADOPOR              74.0
TIPOMODALIDADDESCRIPCION    58.8
TIPOMODALIDAD               57.8
CONSIDERACOMISANT           49.2
IDTIPOCONOCIMIEN            43.1
ORIGENINGRESO               42.9
REFARCHIVO1                 13.2
INGRESORRHH                  4.4
ENESCALAFON                  3.9
FECHAFIN                     1.8
NOMBREPAIS                   0.1
dtype: float64

,TIPODESCRIPCION,AREAACITACIONDESCRIPCION,TIPOMODALIDADDESCRIPCION,NOMBREPAIS,IDCAPACITACION,IDPERSONA,NOMBRE,DURACION,FECHAINICIO,FECHAFIN,TIPOCERTIFICADO,TIPOCAPACITACION,ULTIMO_CAMBIO,FECHAASCENSO,IDPAIS,IDCIUDAD,CERTIFICADOPOR,NAMEARCHDOC,IDTIPOCONOCIMIEN,ENESCALAFON,CONSIDERACOMISANT,REFARCHIVO1,REFARCHIVO2,REFARCHIVO3,REFARCHIVO4,INGRESORRHH,IDUSUARIO,FECHACHECKESCALAFON,TIPOMODALIDAD,IDCANTON,ORIGENINGRESO,FECHASUBIDAARCHIVO,FECHAAPROBACION
0,<NA>,<NA>,VIRTUAL,<NA>,65483,102915,ISFSEA 2025 / CHAOS-PRESERVING FUZZY DIFFERENC...,0.5,2025-05-05,2025-05-06,<NA>,<NA>,2025-05-18 20:09:38.143757,2025-05-18,0,<NA>,The international Society of Fuzzy Sets Extens...,<NA>,<NA>,N,N,"1671198,1574397",<NA>,<NA>,<NA>,N,<NA>,NaT,L,<NA>,<NA>,NaT,NaT
1,<NA>,<NA>,<NA>,ECUADOR,29105,3471,"ESPOLCIENCIA 2007, AFICHES PRIMER LUGAR: METOD...",8.0,2007-11-14,2007-11-14,<NA>,<NA>,2017-04-24 19:07:04.592696,2017-04-19,1,<NA>,<NA>,<NA>,-1,S,S,"128000,127181",<NA>,<NA>,"127999,127180",N,<NA>,2017-04-24,<NA>,<NA>,WEB,NaT,NaT
2,<NA>,<NA>,<NA>,ECUADOR,2060,7374,III CONGRESO INTERNACIONAL DE ACUACULTURA EN A...,32.0,2013-07-11,2013-07-13,<NA>,<NA>,2017-01-30 13:36:57.776130,2014-07-08,1,<NA>,<NA>,EA0908984644-CAP_1_BAYOT_ARROYO_BONNY.PDF,-1,N,N,"19724,19465",<NA>,<NA>,<NA>,S,76217,NaT,<NA>,<NA>,TH,NaT,NaT
3,<NA>,<NA>,<NA>,ECUADOR,2132,5388,I CONGRESO DE FORMACION ACADEMICA ENFOQUE: CAMPO,6.0,2011-12-15,2011-12-16,<NA>,<NA>,2017-02-14 14:01:53.065468,2014-07-15,1,<NA>,<NA>,EA0914776042-FIMCBOR_CAP_2011_1_CALLES_PROCEL.PDF,-1,N,N,"19793,19534",<NA>,<NA>,<NA>,S,76217,NaT,<NA>,<NA>,TH,NaT,NaT
4,<NA>,<NA>,<NA>,ECUADOR,29106,3471,BITWORLD 2002: COMMERCIALIZATION AND DEVELOPME...,24.0,2002-06-03,2002-06-05,<NA>,<NA>,2017-04-24 10:52:03.980839,2017-04-19,1,<NA>,<NA>,<NA>,-1,S,S,"128004,127185",<NA>,<NA>,"128003,127184",N,<NA>,2017-04-24,<NA>,<NA>,WEB,NaT,NaT

## 8. Guardado en data/processed

In [8]:
pc.guardar_procesado(df, 'ponentes_todos.csv')

Guardado: D:\Proyecto_Tesis\data\processed\ponentes_todos.csv (1257 filas x 33 columnas)

WindowsPath('D:/Proyecto_Tesis/data/processed/ponentes_todos.csv')