# 15. Proyectos de investigación disponibles

Proyecto de tesis (Maestria en Ciencia de Datos e IA, ESPOL): *Sistema de Generacion de Perfiles del Personal Docente y Administrativo en ESPOL para la asignacion inteligente de tareas*. Este notebook corresponde a la **Fase 1 y 2** de la metodologia: extraccion y depuracion de una de las fuentes institucionales que alimentan el catalogo de variables (historia laboral, capacitaciones, proyectos, experiencia y direcciones de tesis) usado para construir los perfiles multidimensionales del personal.

**Fuente:** `data/raw/proyectosinvestigaciondisponible.csv`  
**Salida:** `data/processed/proyectos_investigacion_disponible.csv`

Proyectos de investigacion en los que ha participado el personal (tipo, institucion, area de conocimiento, rol, financiamiento).

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd()))
import pandas as pd
import _preprocesamiento_comun as pc

pd.set_option('display.max_columns', 100)

## 1. Carga de datos crudos

In [2]:
df = pc.leer_csv('proyectosinvestigaciondisponible.csv', low_memory=False)
df.head()

Leido proyectosinvestigaciondisponible.csv con encoding=utf-8-sig -> 6768 filas, 51 columnas

,IDPROYECTOINVESTIGACION,TIPO,SUBTIPO,NOMBRE,FECHAINICIO,FECHAFIN,IDPAIS,INSTITUCION_EXTERNA,INSTITUCION_ESPOL,IDPERSONA,IDROLPROYECTO,IDNOMENCLATURATIT,IDNOMENCLATURATIT2,IDAREACONOCIM,IDSUBAREACONOC,IDAREACONOCIM2,IDSUBAREACONOC2,IDAREAFRASCATI,IDSUBAREAFRASCATI,IDAREAFRASCATI2,IDSUBAREAFRASCATI2,RESPONSFINANC,ENESCALAFON,REFARCHIVO1,REFARCHIVO2,REFARCHIVO3,ESTADO_PROYECTO,TABLA,ULTIMO_CAMBIO,ROLPROYECTO,TIPOFINANCIAMIENTOEXTERNO,STRSISTEMA,STRPAIS,STRTIPO,STRSUBTIPO,STRAREACAMPOAMPLIO,STRAREACAMPOESPECIFICO,STRAREACAMPODETALLADO,STRCAMPOAMPLIO,STRCAMPOESPECIFICO,STRCAMPODETALLADO,STRAREACAMPOAMPLIO2,STRAREACAMPOESPECIFICO2,STRAREACAMPODETALLADO2,STRCAMPOAMPLIO2,STRCAMPOESPECIFICO2,STRCAMPODETALLADO2,STRAREAFRASCATI,STRSUBAREAFRASCATI,STRAREAFRASCATI2,STRSUBAREAFRASCATI2
0,3100,I,2,DESEMPEÑO AMBIENTAL DEL CEMENTO Y EL CONCRETO ...,2020-05-03-00.00.00.000000,2024-06-30-00.00.00.000000,1,HOLCIM,FACULTAD DE INGENIERÍA EN MECÁNICA Y CIENCIAS ...,1178,1,314.0,460.0,8,2,6,2,2,7,2,5,MAESTRÍA ECOEFICIENCIA INDUSTRIAL (PAGO A DIRE...,NaN,https://gestionproyectos.espol.edu.ec/UPLOADS/...,https://gestionproyectos.espol.edu.ec/UPLOADS/...,NaN,FINALIZADO,I,2024-01-17-11.49.14.289970,DIRECTOR,0,INVESTIGACION,ECUADOR,Investigacion,Aplicada,"Ingeniería, industria y construcción",Industria y producción,NaN,7.0,2.0,0.0,"Ciencias naturales, matemáticas y estadística",Medio ambiente,NaN,5.0,2.0,0.0,Engineering and Technology,Environmental engineering,Engineering and Technology,Materials engineering
1,5694,I,3,"RECOMP–RECYCLED COMPOSITES FOR ENGINEERING, DE...",2026-02-02-00.00.00.000000,2028-02-18-00.00.00.000000,1,UNIVERSIDAD DE GUAYAQUIL,FACULTAD DE INGENIERÍA EN MECÁNICA Y CIENCIAS ...,674686,4,267.0,267.0,8,1,8,1,2,3,2,5,ESPOL,NaN,https://gestionproyectos.espol.edu.ec/UPLOADS/...,NaN,https://gestionproyectos.espol.edu.ec/UPLOADS/...,APROBADO Y EN EJECUCIÓN,I,2026-04-23-13.43.31.483729,CO-DIRECTOR,0,INVESTIGACION,ECUADOR,Investigacion,Desarrollo,"Ingeniería, industria y construcción",Ingeniería y profesiones afines,NaN,7.0,1.0,0.0,"Ingeniería, industria y construcción",Ingeniería y profesiones afines,NaN,7.0,1.0,0.0,Engineering and Technology,Mechanical engineering,Engineering and Technology,Materials engineering
2,3100,I,2,DESEMPEÑO AMBIENTAL DEL CEMENTO Y EL CONCRETO ...,2020-05-03-00.00.00.000000,2024-06-30-00.00.00.000000,1,HOLCIM,FACULTAD DE INGENIERÍA EN MECÁNICA Y CIENCIAS ...,73715,4,314.0,460.0,8,2,6,2,2,7,2,5,MAESTRÍA ECOEFICIENCIA INDUSTRIAL (PAGO A DIRE...,NaN,https://gestionproyectos.espol.edu.ec/UPLOADS/...,https://gestionproyectos.espol.edu.ec/UPLOADS/...,NaN,FINALIZADO,I,2024-01-17-11.49.14.289970,PARTICIPANTE,0,INVESTIGACION,ECUADOR,Investigacion,Aplicada,"Ingeniería, industria y construcción",Industria y producción,NaN,7.0,2.0,0.0,"Ciencias naturales, matemáticas y estadística",Medio ambiente,NaN,5.0,2.0,0.0,Engineering and Technology,Environmental engineering,Engineering and Technology,Materials engineering
3,5694,I,3,"RECOMP–RECYCLED COMPOSITES FOR ENGINEERING, DE...",2026-02-02-00.00.00.000000,2028-02-18-00.00.00.000000,1,UNIVERSIDAD DE GUAYAQUIL,FACULTAD DE INGENIERÍA EN MECÁNICA Y CIENCIAS ...,55753,1,267.0,267.0,8,1,8,1,2,3,2,5,ESPOL,NaN,https://gestionproyectos.espol.edu.ec/UPLOADS/...,NaN,https://gestionproyectos.espol.edu.ec/UPLOADS/...,APROBADO Y EN EJECUCIÓN,I,2026-04-23-13.43.31.483729,DIRECTOR,0,INVESTIGACION,ECUADOR,Investigacion,Desarrollo,"Ingeniería, industria y construcción",Ingeniería y profesiones afines,NaN,7.0,1.0,0.0,"Ingeniería, industria y construcción",Ingeniería y profesiones afines,NaN,7.0,1.0,0.0,Engineering and Technology,Mechanical engineering,Engineering and Technology,Materials engineering
4,5694,I,3,"RECOMP–RECYCLED COMPOSITES FOR ENGINEERING, DE...",2026-02-02-00.00.00.000000,2028-02-18-00.00.00.000000,1,UNIVERSIDAD DE GUAYAQUIL,FACULTAD DE INGENIERÍA EN MECÁNICA Y CIENCIAS ...,1586,4,267.0,267.0,8,1,8,1,2,3,2,5,ESPOL,NaN,https://gestionproyectos.espol.edu.ec/UPLOADS/...,NaN,https://gestionproyectos.espol.edu.ec/UPLOADS/...,APROBADO Y EN EJECUCIÓN,I,2026-04-23-13.43.31.483729,PARTICIPANTE,0,INVESTIGACION,ECUADOR,Investigacion,Desarrollo,"Ingeniería, industria y construcción",Ingeniería y profesiones afines,NaN,7.0,1.0,0.0,"Ingeniería, industria y construcción",Ingeniería y profesiones afines,NaN,7.0,1.0,0.0,Engineering and Technology,Mechanical engineering,Engineering and Technology,Materials engineering

## 2. Exploración inicial

In [3]:
pc.resumen(df, 'proyectos_investigacion_disponible')

--- Resumen proyectos_investigacion_disponible ---
Dimensiones: 6768 filas x 51 columnas
Filas duplicadas: 0
Columnas con nulos (%):
STRAREACAMPODETALLADO2     100.0
STRAREACAMPODETALLADO      100.0
ENESCALAFON                 96.7
STRSUBAREAFRASCATI2         87.9
STRAREAFRASCATI2            87.9
STRAREACAMPOAMPLIO2         84.9
STRAREACAMPOESPECIFICO2     84.9
STRCAMPOAMPLIO2             84.9
IDNOMENCLATURATIT2          84.9
STRCAMPOESPECIFICO2         84.9
STRCAMPODETALLADO2          84.9
REFARCHIVO3                 55.6
REFARCHIVO2                 45.7
REFARCHIVO1                 38.6
INSTITUCION_EXTERNA         35.8
INSTITUCION_ESPOL            2.3
IDNOMENCLATURATIT            1.3
STRCAMPOAMPLIO               1.3
STRCAMPOESPECIFICO           1.3
STRAREACAMPOAMPLIO           1.3
STRCAMPODETALLADO            1.3
STRAREACAMPOESPECIFICO       1.3
STRSUBTIPO                   0.3
RESPONSFINANC                0.1
dtype: float64

In [4]:
df.dtypes

IDPROYECTOINVESTIGACION        int64
TIPO                             str
SUBTIPO                        int64
NOMBRE                           str
FECHAINICIO                      str
FECHAFIN                         str
IDPAIS                         int64
INSTITUCION_EXTERNA              str
INSTITUCION_ESPOL                str
IDPERSONA                      int64
IDROLPROYECTO                  int64
IDNOMENCLATURATIT            float64
IDNOMENCLATURATIT2           float64
IDAREACONOCIM                  int64
IDSUBAREACONOC                 int64
IDAREACONOCIM2                 int64
IDSUBAREACONOC2                int64
IDAREAFRASCATI                 int64
IDSUBAREAFRASCATI              int64
IDAREAFRASCATI2                int64
IDSUBAREAFRASCATI2             int64
RESPONSFINANC                    str
ENESCALAFON                      str
REFARCHIVO1                      str
REFARCHIVO2                      str
REFARCHIVO3                      str
ESTADO_PROYECTO                  str
TABLA                            str
ULTIMO_CAMBIO                    str
ROLPROYECTO                      str
TIPOFINANCIAMIENTOEXTERNO      int64
STRSISTEMA                       str
STRPAIS                          str
STRTIPO                          str
STRSUBTIPO                       str
STRAREACAMPOAMPLIO               str
STRAREACAMPOESPECIFICO           str
STRAREACAMPODETALLADO        float64
STRCAMPOAMPLIO               float64
STRCAMPOESPECIFICO           float64
STRCAMPODETALLADO            float64
STRAREACAMPOAMPLIO2              str
STRAREACAMPOESPECIFICO2          str
STRAREACAMPODETALLADO2       float64
STRCAMPOAMPLIO2              float64
STRCAMPOESPECIFICO2          float64
STRCAMPODETALLADO2           float64
STRAREAFRASCATI                  str
STRSUBAREAFRASCATI               str
STRAREAFRASCATI2                 str
STRSUBAREAFRASCATI2              str
dtype: object

## 3. Limpieza

In [5]:
df = pc.limpiar_strings(df)
df = pc.quitar_columnas_vacias(df, umbral=0.99)
df = pc.quitar_columnas_constantes(df)

Columnas eliminadas por tener >= 99% de nulos: ['STRAREACAMPODETALLADO', 'STRAREACAMPODETALLADO2']
Columnas eliminadas por ser constantes: ['TABLA', 'STRSISTEMA', 'STRCAMPODETALLADO', 'STRCAMPODETALLADO2']

## 5. Tipado de fechas e identificadores

In [6]:
df = pc.castear_fechas(df, ['FECHAINICIO', 'FECHAFIN', 'ULTIMO_CAMBIO'])
df = pc.castear_enteros(df, ['IDPROYECTOINVESTIGACION', 'IDPERSONA', 'IDPAIS', 'IDROLPROYECTO', 'IDNOMENCLATURATIT', 'IDNOMENCLATURATIT2', 'IDAREACONOCIM', 'IDSUBAREACONOC', 'IDAREACONOCIM2', 'IDSUBAREACONOC2', 'IDAREAFRASCATI', 'IDSUBAREAFRASCATI', 'IDAREAFRASCATI2', 'IDSUBAREAFRASCATI2'])

## 7. Verificación final

In [7]:
pc.resumen(df, 'proyectos_investigacion_disponible (procesado)')
df.head()

--- Resumen proyectos_investigacion_disponible (procesado) ---
Dimensiones: 6768 filas x 45 columnas
Filas duplicadas: 0
Columnas con nulos (%):
ENESCALAFON                96.7
STRSUBAREAFRASCATI2        87.9
STRAREAFRASCATI2           87.9
STRAREACAMPOESPECIFICO2    84.9
IDNOMENCLATURATIT2         84.9
STRCAMPOAMPLIO2            84.9
STRCAMPOESPECIFICO2        84.9
STRAREACAMPOAMPLIO2        84.9
REFARCHIVO3                55.6
REFARCHIVO2                45.7
REFARCHIVO1                38.6
INSTITUCION_EXTERNA        35.8
INSTITUCION_ESPOL           2.3
STRAREACAMPOESPECIFICO      1.3
IDNOMENCLATURATIT           1.3
STRCAMPOAMPLIO              1.3
STRCAMPOESPECIFICO          1.3
STRAREACAMPOAMPLIO          1.3
STRSUBTIPO                  0.3
RESPONSFINANC               0.1
dtype: float64

,IDPROYECTOINVESTIGACION,TIPO,SUBTIPO,NOMBRE,FECHAINICIO,FECHAFIN,IDPAIS,INSTITUCION_EXTERNA,INSTITUCION_ESPOL,IDPERSONA,IDROLPROYECTO,IDNOMENCLATURATIT,IDNOMENCLATURATIT2,IDAREACONOCIM,IDSUBAREACONOC,IDAREACONOCIM2,IDSUBAREACONOC2,IDAREAFRASCATI,IDSUBAREAFRASCATI,IDAREAFRASCATI2,IDSUBAREAFRASCATI2,RESPONSFINANC,ENESCALAFON,REFARCHIVO1,REFARCHIVO2,REFARCHIVO3,ESTADO_PROYECTO,ULTIMO_CAMBIO,ROLPROYECTO,TIPOFINANCIAMIENTOEXTERNO,STRPAIS,STRTIPO,STRSUBTIPO,STRAREACAMPOAMPLIO,STRAREACAMPOESPECIFICO,STRCAMPOAMPLIO,STRCAMPOESPECIFICO,STRAREACAMPOAMPLIO2,STRAREACAMPOESPECIFICO2,STRCAMPOAMPLIO2,STRCAMPOESPECIFICO2,STRAREAFRASCATI,STRSUBAREAFRASCATI,STRAREAFRASCATI2,STRSUBAREAFRASCATI2
0,3100,I,2,DESEMPEÑO AMBIENTAL DEL CEMENTO Y EL CONCRETO ...,2020-05-03,2024-06-30,1,HOLCIM,FACULTAD DE INGENIERÍA EN MECÁNICA Y CIENCIAS ...,1178,1,314,460,8,2,6,2,2,7,2,5,MAESTRÍA ECOEFICIENCIA INDUSTRIAL (PAGO A DIRE...,<NA>,https://gestionproyectos.espol.edu.ec/UPLOADS/...,https://gestionproyectos.espol.edu.ec/UPLOADS/...,<NA>,FINALIZADO,2024-01-17 11:49:14.289970,DIRECTOR,0,ECUADOR,Investigacion,Aplicada,"Ingeniería, industria y construcción",Industria y producción,7.0,2.0,"Ciencias naturales, matemáticas y estadística",Medio ambiente,5.0,2.0,Engineering and Technology,Environmental engineering,Engineering and Technology,Materials engineering
1,5694,I,3,"RECOMP–RECYCLED COMPOSITES FOR ENGINEERING, DE...",2026-02-02,2028-02-18,1,UNIVERSIDAD DE GUAYAQUIL,FACULTAD DE INGENIERÍA EN MECÁNICA Y CIENCIAS ...,674686,4,267,267,8,1,8,1,2,3,2,5,ESPOL,<NA>,https://gestionproyectos.espol.edu.ec/UPLOADS/...,<NA>,https://gestionproyectos.espol.edu.ec/UPLOADS/...,APROBADO Y EN EJECUCIÓN,2026-04-23 13:43:31.483729,CO-DIRECTOR,0,ECUADOR,Investigacion,Desarrollo,"Ingeniería, industria y construcción",Ingeniería y profesiones afines,7.0,1.0,"Ingeniería, industria y construcción",Ingeniería y profesiones afines,7.0,1.0,Engineering and Technology,Mechanical engineering,Engineering and Technology,Materials engineering
2,3100,I,2,DESEMPEÑO AMBIENTAL DEL CEMENTO Y EL CONCRETO ...,2020-05-03,2024-06-30,1,HOLCIM,FACULTAD DE INGENIERÍA EN MECÁNICA Y CIENCIAS ...,73715,4,314,460,8,2,6,2,2,7,2,5,MAESTRÍA ECOEFICIENCIA INDUSTRIAL (PAGO A DIRE...,<NA>,https://gestionproyectos.espol.edu.ec/UPLOADS/...,https://gestionproyectos.espol.edu.ec/UPLOADS/...,<NA>,FINALIZADO,2024-01-17 11:49:14.289970,PARTICIPANTE,0,ECUADOR,Investigacion,Aplicada,"Ingeniería, industria y construcción",Industria y producción,7.0,2.0,"Ciencias naturales, matemáticas y estadística",Medio ambiente,5.0,2.0,Engineering and Technology,Environmental engineering,Engineering and Technology,Materials engineering
3,5694,I,3,"RECOMP–RECYCLED COMPOSITES FOR ENGINEERING, DE...",2026-02-02,2028-02-18,1,UNIVERSIDAD DE GUAYAQUIL,FACULTAD DE INGENIERÍA EN MECÁNICA Y CIENCIAS ...,55753,1,267,267,8,1,8,1,2,3,2,5,ESPOL,<NA>,https://gestionproyectos.espol.edu.ec/UPLOADS/...,<NA>,https://gestionproyectos.espol.edu.ec/UPLOADS/...,APROBADO Y EN EJECUCIÓN,2026-04-23 13:43:31.483729,DIRECTOR,0,ECUADOR,Investigacion,Desarrollo,"Ingeniería, industria y construcción",Ingeniería y profesiones afines,7.0,1.0,"Ingeniería, industria y construcción",Ingeniería y profesiones afines,7.0,1.0,Engineering and Technology,Mechanical engineering,Engineering and Technology,Materials engineering
4,5694,I,3,"RECOMP–RECYCLED COMPOSITES FOR ENGINEERING, DE...",2026-02-02,2028-02-18,1,UNIVERSIDAD DE GUAYAQUIL,FACULTAD DE INGENIERÍA EN MECÁNICA Y CIENCIAS ...,1586,4,267,267,8,1,8,1,2,3,2,5,ESPOL,<NA>,https://gestionproyectos.espol.edu.ec/UPLOADS/...,<NA>,https://gestionproyectos.espol.edu.ec/UPLOADS/...,APROBADO Y EN EJECUCIÓN,2026-04-23 13:43:31.483729,PARTICIPANTE,0,ECUADOR,Investigacion,Desarrollo,"Ingeniería, industria y construcción",Ingeniería y profesiones afines,7.0,1.0,"Ingeniería, industria y construcción",Ingeniería y profesiones afines,7.0,1.0,Engineering and Technology,Mechanical engineering,Engineering and Technology,Materials engineering

## 8. Guardado en data/processed

In [8]:
pc.guardar_procesado(df, 'proyectos_investigacion_disponible.csv')

Guardado: D:\Proyecto_Tesis\data\processed\proyectos_investigacion_disponible.csv (6768 filas x 45 columnas)

WindowsPath('D:/Proyecto_Tesis/data/processed/proyectos_investigacion_disponible.csv')