# 16. Proyectos de vinculación disponibles

Proyecto de tesis (Maestria en Ciencia de Datos e IA, ESPOL): *Sistema de Generacion de Perfiles del Personal Docente y Administrativo en ESPOL para la asignacion inteligente de tareas*. Este notebook corresponde a la **Fase 1 y 2** de la metodologia: extraccion y depuracion de una de las fuentes institucionales que alimentan el catalogo de variables (historia laboral, capacitaciones, proyectos, experiencia y direcciones de tesis) usado para construir los perfiles multidimensionales del personal.

**Fuente:** `data/raw/proyectosvinculaciondisponible.csv`  
**Salida:** `data/processed/proyectos_vinculacion_disponible.csv`

Proyectos de vinculacion con la sociedad en los que ha participado el personal.

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd()))
import pandas as pd
import _preprocesamiento_comun as pc

pd.set_option('display.max_columns', 100)

## 1. Carga de datos crudos

In [2]:
df = pc.leer_csv('proyectosvinculaciondisponible.csv', low_memory=False)
df.head()

Leido proyectosvinculaciondisponible.csv con encoding=utf-8-sig -> 2659 filas, 17 columnas

,IDPERSONA,IDPROYECTOINVESTIGACION,NOMBREPROYECTO,NOMBREPROGRAMA,TIPO,IDAREACONOCIM,FECHAINICIO,FECHAFIN,REFARCHIVO1,REFARCHIVO2,REFARCHIVO3,ROLPROYECTO,TABLA,REVISADOENESCALAFON,ENESCALAFON,ESTIMULO,IDVSPROYECTOCOL
0,1252,225,Diseño e implementación de un sistema de infor...,Excelencia Hospitalaria,V,NaN,NaN,NaN,https://practicas.espol.edu.ec/Proyecto/Proyec...,NaN,NaN,DIRECTOR DE PROYECTO,V,NaN,NaN,NaN,0
1,2283,217,Fortalecimiento a comunidades del Golfo de Gua...,Fortalecimiento de las capacidades de manejo y...,V,NaN,NaN,NaN,https://practicas.espol.edu.ec/Proyecto/Proyec...,NaN,NaN,DIRECTOR DE PROGRAMA,V,NaN,NaN,NaN,0
2,2283,213,Implementación de un Plan Piloto de Comerciali...,Fortalecimiento de las capacidades de manejo y...,V,NaN,NaN,NaN,https://practicas.espol.edu.ec/Proyecto/Proyec...,NaN,NaN,DIRECTOR DE PROYECTO,V,NaN,NaN,NaN,0
3,2701,222,Centro de Atención Gratuita. (Gastos Generales),Centro de Atención Gratuita,V,NaN,NaN,NaN,https://practicas.espol.edu.ec/Proyecto/Proyec...,NaN,NaN,DIRECTOR DE PROGRAMA,V,NaN,NaN,NaN,0
4,2701,226,Fortalecimiento de microempresas a través del ...,Centro de Atención Gratuita,V,NaN,NaN,NaN,https://practicas.espol.edu.ec/Proyecto/Proyec...,NaN,NaN,DIRECTOR DE PROGRAMA,V,NaN,NaN,NaN,0

## 2. Exploración inicial

In [3]:
pc.resumen(df, 'proyectos_vinculacion_disponible')

--- Resumen proyectos_vinculacion_disponible ---
Dimensiones: 2659 filas x 17 columnas
Filas duplicadas: 0
Columnas con nulos (%):
REVISADOENESCALAFON    100.0
REFARCHIVO3            100.0
ESTIMULO               100.0
REFARCHIVO2            100.0
ENESCALAFON             99.7
IDAREACONOCIM            6.8
FECHAINICIO              2.1
FECHAFIN                 2.0
dtype: float64

In [4]:
df.dtypes

IDPERSONA                    int64
IDPROYECTOINVESTIGACION      int64
NOMBREPROYECTO                 str
NOMBREPROGRAMA                 str
TIPO                           str
IDAREACONOCIM                  str
FECHAINICIO                    str
FECHAFIN                       str
REFARCHIVO1                    str
REFARCHIVO2                float64
REFARCHIVO3                float64
ROLPROYECTO                    str
TABLA                          str
REVISADOENESCALAFON        float64
ENESCALAFON                    str
ESTIMULO                   float64
IDVSPROYECTOCOL              int64
dtype: object

## 3. Limpieza

In [5]:
df = pc.limpiar_strings(df)
df = pc.quitar_columnas_vacias(df, umbral=0.99)
df = pc.quitar_columnas_constantes(df)

Columnas eliminadas por tener >= 99% de nulos: ['REFARCHIVO2', 'REFARCHIVO3', 'REVISADOENESCALAFON', 'ENESCALAFON', 'ESTIMULO']
Columnas eliminadas por ser constantes: ['TIPO', 'TABLA']

## 5. Tipado de fechas e identificadores

In [6]:
df = pc.castear_fechas(df, ['FECHAINICIO', 'FECHAFIN'])
df = pc.castear_enteros(df, ['IDPERSONA', 'IDPROYECTOINVESTIGACION', 'IDAREACONOCIM', 'IDVSPROYECTOCOL'])

## 7. Verificación final

In [7]:
pc.resumen(df, 'proyectos_vinculacion_disponible (procesado)')
df.head()

--- Resumen proyectos_vinculacion_disponible (procesado) ---
Dimensiones: 2659 filas x 10 columnas
Filas duplicadas: 0
Columnas con nulos (%):
IDAREACONOCIM    100.0
FECHAINICIO        2.1
FECHAFIN           2.0
dtype: float64

,IDPERSONA,IDPROYECTOINVESTIGACION,NOMBREPROYECTO,NOMBREPROGRAMA,IDAREACONOCIM,FECHAINICIO,FECHAFIN,REFARCHIVO1,ROLPROYECTO,IDVSPROYECTOCOL
0,1252,225,Diseño e implementación de un sistema de infor...,Excelencia Hospitalaria,<NA>,NaT,NaT,https://practicas.espol.edu.ec/Proyecto/Proyec...,DIRECTOR DE PROYECTO,0
1,2283,217,Fortalecimiento a comunidades del Golfo de Gua...,Fortalecimiento de las capacidades de manejo y...,<NA>,NaT,NaT,https://practicas.espol.edu.ec/Proyecto/Proyec...,DIRECTOR DE PROGRAMA,0
2,2283,213,Implementación de un Plan Piloto de Comerciali...,Fortalecimiento de las capacidades de manejo y...,<NA>,NaT,NaT,https://practicas.espol.edu.ec/Proyecto/Proyec...,DIRECTOR DE PROYECTO,0
3,2701,222,Centro de Atención Gratuita. (Gastos Generales),Centro de Atención Gratuita,<NA>,NaT,NaT,https://practicas.espol.edu.ec/Proyecto/Proyec...,DIRECTOR DE PROGRAMA,0
4,2701,226,Fortalecimiento de microempresas a través del ...,Centro de Atención Gratuita,<NA>,NaT,NaT,https://practicas.espol.edu.ec/Proyecto/Proyec...,DIRECTOR DE PROGRAMA,0

## 8. Guardado en data/processed

In [8]:
pc.guardar_procesado(df, 'proyectos_vinculacion_disponible.csv')

Guardado: D:\Proyecto_Tesis\data\processed\proyectos_vinculacion_disponible.csv (2659 filas x 10 columnas)

WindowsPath('D:/Proyecto_Tesis/data/processed/proyectos_vinculacion_disponible.csv')